gadai/accounts/urls.py
from django.conf.urls.defaults import patterns
from django.contrib.auth import views as authviews

urlpatterns = patterns('', 
    (r'^login/$',                authviews.login),
    (r'^logout/$',               authviews.logout_then_login),
    (r'^password/change/$',      authviews.password_change),
    (r'^password/change/done/$', authviews.password_change_done),
)

gadai/appgadai/kas/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail, create_update, date_based
from gadai.appgadai.models import MutasiKas, KasBank
from gadai.appgadai.kas.forms import MutasiKasForm
from gadai.appgadai.kas.views import rekening_show,mutasikas_add,mutasikas_bulan,rekening_pindahbuku
import datetime

MONTH_SHOW = 3 * 30
now = datetime.date.today()
since = now - datetime.timedelta(MONTH_SHOW)
date_list = MutasiKas.objects.filter(tanggal__gt=since).dates('tanggal', 'day')

cashflow_list = [{'tanggal': d,
        'penerimaan': sum([m.nilai for m in MutasiKas.objects.filter(tanggal=d) if m.is_debet]),
        'pengeluaran': sum([abs(m.nilai) for m in MutasiKas.objects.filter(tanggal=d) if not m.is_debet])} for d in date_list]


urlpatterns = patterns('',
    url(r'^$',  list_detail.object_list, {
        'queryset': MutasiKas.objects.all(),
        'template_name': 'kas/mutasikas_archive.html',
        'extra_context': {'cashflow_list': cashflow_list, 
            'date_list': MutasiKas.objects.dates('tanggal', 'month')}}),
    url(r'^add/$', mutasikas_add),
    url(r'^arsip/(?P<tahun>\d{4})/(?P<bulan>\d{2})/$', mutasikas_bulan),
    url(r'^rekening/(?P<object_id>\d+)/$', rekening_show),
    url(r'rekening/pindahbuku/', rekening_pindahbuku),
)

gadai/djangoChat/urls.py
from django.conf.urls import patterns, url

from djangoChat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^api/$',views.chat_api,name='chat_api'),
    url(r'^api/users/$',views.logged_chat_users,name='logged_chat_users'),
    url(r'^api/users/update/$',views.update_time,name='update_time')
)

gadai/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.static import serve
from django.views.generic import list_detail, create_update
admin.autodiscover()
from django.conf import settings
import os
from gadai.appgadai.views import homepage

urlpatterns = patterns('',
    url(r'^pencairan/',include('gadai.appgadai.pencairan.urls')),
    url(r'^gudang/',include('gadai.appgadai.gudang.urls')),
    url(r'^admgudang/',include('gadai.appgadai.admgudang.urls')),
    url(r'^parameter/',include('gadai.appkeuangan.parameter.urls')),
    url(r'^rreport/',include('gadai.appkeuangan.report.urls')),
    url(r'^rkeuangan/',include('gadai.appkeuangan.keuangan.urls')),
    url(r'^parameterjurnal/',include('gadai.appgadai.parameterjurnal.urls')),
    url(r'^materaicabang/',include('gadai.appgadai.materaicabang.urls')),
    url(r'^kplgerai/',include('gadai.appgadai.kplgerai.urls')),
    url(r'^mankeu/',include('gadai.appgadai.mankeu.urls')),
    url(r'^kasirgerai/', include('gadai.appgadai.kasirgerai.urls')),
    url(r'^manop/',include('gadai.appgadai.manop.urls')),
    url(r'^accounts/',include('gadai.accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',homepage),
    url(r'^setting/',    include('gadai.appgadai.setting.urls')),
    url(r'^akadgadai/', include('gadai.appgadai.akadgadai.urls')),
    url(r'^gerai/', include('gadai.appgadai.gerai.urls')),
    url(r'^nasabah/', include('gadai.appgadai.nasabah.urls')),
    url(r'^taksir/', include('gadai.appgadai.taksir.urls')),
    url(r'^jurnal/',include('gadai.appgadai.jurnal.urls')),
    url(r'^barang/',include('gadai.appgadai.barang.urls')),
    url(r'^pelunasan/',include('gadai.appgadai.pelunasan.urls')),
    url(r'^biaya/',include('gadai.appgadai.biaya.urls')),
    url(r'^lelang/',include('gadai.appgadai.lelang.urls')),##firman
    url(r'^piutang/',include('gadai.appgadai.piutang.urls')),
    url(r'^permintaan/',include('gadai.appgadai.permintaan.urls')),
    url(r'^report/',include('gadai.appgadai.report.urls')),
    url(r'^keuangan/',include('gadai.appgadai.keuangan.urls')),
    url(r'^biayamaterai/',include('gadai.appgadai.biayamaterai.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', serve, {'document_root' : os.path.join(os.path.dirname(__file__),("static"))})
    )

gadai/appgadai/admgudang/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms

class AdmGudangForm(forms.ModelForm):
    tanggal = forms.DateField(widget=forms.widgets.DateInput(attrs={'readonly':'False'}, format="%d-%m-%Y"))
    class Meta:
        model = AdmGudang
        widgets = {
            'adm' : forms.HiddenInput(),
        }

gadai/appgadai/akadgadai/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from django.core.exceptions import ValidationError
from chosen import forms as chosenforms
from django.utils.safestring import mark_safe

STATUS_OTORISASI_MANOP=(
    ('1','STATUS'),
    ('2','OTORISASI'),
)
class UploadPKForm(forms.Form):
    berkas_pk = forms.FileField()

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class PencarianSopForm(forms.Form):
    cari = chosenforms.ChosenModelChoiceField(queryset=Master_Sop.objects.filter(status_sop =2),widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_barang','size': 22,}))
           

class TambahSopForm(forms.Form):
    judul_sop = forms.CharField(max_length=35,widget=forms.TextInput(attrs={'placeholder':'Judul','class': 'r_nama'}))
    tanggal_sop = forms.DateField(widget=forms.TextInput(attrs={'placeholder':'(Tanggal-Bulan-Tahun)'}))
    status_sop = forms.ChoiceField(widget=forms.Select(attrs={'readonly':'True'}),choices=AKTIFASI_PARAMETER,initial='2')

    gambar = forms.FileField()
    judul = forms.CharField(max_length=35,widget=forms.TextInput(attrs={'placeholder':'Judul','class': 'r_nama'}))
    deskripsi = forms.CharField(max_length=35,widget=forms.TextInput(attrs={'placeholder':'Deskripsi','class': 'r_nama'}))
    no_urut = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value':0}))
    tanggal = forms.DateField(widget=forms.TextInput(attrs={'placeholder':'(Tanggal-Bulan-Tahun)'}))

class Verifikasi_ManOpForm(ModelForm):
    tanggal = forms.DateField(widget=forms.widgets.DateInput(attrs={'size': 12,'readonly':'True'}, format="%d-%m-%Y"))
    class Meta:
        model = ManopGadai

class Edit_AkadForm(ModelForm):
    class Meta:
        model = AkadGadai
        #fields = ('agnasabah','gerai','tanggal','nilai','taksir','barang','bea_materai','jenis_transaksi','jangka_waktu_kendaraan','jatuhtempo')
        widgets = {
            'agnasabah' : forms.HiddenInput(),
            'status_transaksi' : forms.HiddenInput(),
            #'tanggal':forms.HiddenInput(),
            'status_taksir' : forms.HiddenInput(),
            #'jatuhtempo': forms.HiddenInput(),
            'nocoa_titipan': forms.HiddenInput(),
            'nocoa_kas': forms.HiddenInput(),
            'os_pokok': forms.HiddenInput(),
            'status_kw': forms.HiddenInput(),
            'status_kwlunas': forms.HiddenInput(),
            'status_mcc': forms.HiddenInput(),
            'lunas': forms.HiddenInput(),
            'status_transaksi': forms.HiddenInput(),
            'selisih_pelunasan':forms.HiddenInput(),
        }

class AkadGadaiForm(ModelForm):
    agnasabah = forms.ModelChoiceField(label = "NAMA NASABAH",queryset=Nasabah.objects.all())
    tanggal = forms.DateField(label = "Tanggal Akad",widget=forms.TextInput(attrs={'size': 10}))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all(),empty_label="--- PILIH ---")
    jangka_waktu = forms.ChoiceField( widget = forms.Select(), choices = JANGKA_WAKTU)
    nilai = forms.IntegerField(label="Nilai Taksir",widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    taksir = forms.ModelChoiceField(queryset=Taksir.objects.filter(status = 2),empty_label="--- PILIH ---")
    denda = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    terlambat = forms.IntegerField(widget=forms.TextInput())
    status_transaksi =forms.ChoiceField(widget=forms.Select(),choices=CHOICES_TRANSAKSI)

    class Meta:
        model = AkadGadai

class PelunasanForm(forms.Form):
    pelunasan = forms.ModelChoiceField(queryset=AkadGadai.objects.filter(lunas__isnull=True))
    tanggal = forms.DateField(initial=datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    jatuhtempo = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    tgl_akad = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    
    nilai = forms.IntegerField(widget=forms.TextInput(attrs={'readonly':'True','size': 9, 'alt': 'integer', 'class': 'rp_nilai uang','onfocus':'total_dibayar()'}))
    denda = forms.IntegerField(widget=forms.TextInput(attrs={'readonly':'True','size': 9, 'value': '0','alt': 'integer',\
    'class': 'rp_nilai uang','onclick':'total_dibayar()'}))
    terlambat = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value':0}))
    bea_jasa = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'value': '0', 'alt': 'integer', 'class': 'rp_nilai uang','onfocus':'total_dibayar()'}))
    jenis_barang =forms.ChoiceField(choices=CHOICES_JENIS_TRANSAKSI,widget=forms.RadioSelect(attrs={'class':'rad','onfocus':'total_dibayar()'}))
    denda_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'readonly':'True','size': 9, 'value': '0', 'alt': 'integer', 'class': 'rp_nilai uang','onfocus':'total_dibayar()'}))
    terlambat_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value':0}))
    bea_jasa_kendaraan = forms.DecimalField(widget=forms.TextInput(attrs={'readonly':'True','size': 9,'class': 'rp_nilai uang','value':0}))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    status_transaksi =forms.ChoiceField(widget=forms.Select(attrs={'readonly':'True'}),choices=CHOICES_TRANSAKSI) 
    lunas = forms.BooleanField(required=False)
    total = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'alt': 'integer', 'class': 'rp_nilai uang','readonly':True,'onfocus':'total_dibayar()'}))
    total_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'alt': 'integer', 'class': 'rp_nilai uang','readonly':True,'onfocus':'total_dibayar()','value':0}))
    norek = forms.CharField( widget=forms.TextInput(attrs={'size':20,'readonly':'true'}))
    status = forms.ChoiceField(widget=forms.Select(attrs={'readonly':'False'}),choices=STATUS_OTORISASI)
    comment = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Masukan Keterangan Nilai Yg ingin Ada Diskon'}),required=False)
    class Meta:
        model = Pelunasan    

class PelunasanDiskonForm(forms.Form):
    pelunasan = forms.ModelChoiceField(queryset=AkadGadai.objects.filter(lunas__isnull=True))
    tanggal = forms.DateField(initial=datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'false'}, format="%d-%m-%Y"))
    jatuhtempo = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    tgl_akad = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    nilai = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'alt': 'integer', 'class': 'rp_nilai uang'}))
    denda = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'value': '0','alt': 'integer', 'class': 'rp_nilai uang'}))
    terlambat = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value':0}))
    bea_jasa = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'value': '0', 'alt': 'integer', 'class': 'rp_nilai uang'}))
    jenis_barang =forms.ChoiceField(choices=CHOICES_JENIS_TRANSAKSI,widget=forms.RadioSelect(attrs={'class':'rad'}))
    denda_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'readonly':'True','size': 9, 'value': '0', 'alt': 'integer', 'class': 'rp_nilai uang','onclick':'total_dibayar()'}))
    terlambat_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value':0}))
    bea_jasa_kendaraan = forms.DecimalField(widget=forms.TextInput(attrs={'readonly':'True','size': 9,'class': 'rp_nilai uang','alt': 'integer'}))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    status_transaksi =forms.ChoiceField(widget=forms.Select(attrs={'readonly':'True'}),choices=CHOICES_TRANSAKSI) 
    lunas = forms.BooleanField(required=False)
    total = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'alt': 'integer', 'class': 'rp_nilai uang','readonly':True}))
    total_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'size': 9, 'alt': 'integer', 'class': 'rp_nilai uang','readonly':True}))
    norek = forms.CharField( widget=forms.TextInput(attrs={'size':20,'readonly':'true'}))
    status = forms.ChoiceField(widget=forms.Select(attrs={'readonly':'False'}),choices=STATUS_OTORISASI_MANOP, initial='2',required=False)
    comment = forms.CharField(widget=forms.Textarea(attrs={'cols': 10, 'rows': 20}),required=False)

    class Meta:
        model = Pelunasan


class AkadForm(forms.Form):
    
    agnasabah = forms.ModelChoiceField(label = "NAMA NASABAH",queryset=Nasabah.objects.filter(id__isnull=False))
    tanggal = forms.DateTimeField(initial = datetime.date.today,widget=forms.DateTimeInput(attrs={'readonly':'true'}))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all(),empty_label="--- PILIH ---")
    jangka_waktu = forms.ChoiceField( widget = forms.Select(), choices = JANGKA_WAKTU)
    nilai = forms.IntegerField(label="Nilai Taksir",widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    taksir = chosenforms.ChosenModelChoiceField(label = "Data Taksir",queryset=Taksir.objects.filter(status = 2),widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_account'}))
    bea_materai = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    barang = chosenforms.ChosenModelChoiceField(queryset=Barang.objects.all(),widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_barang'}))
    jenis_transaksi=forms.ChoiceField(choices=CHOICES_JENIS_TRANSAKSI,widget=forms.RadioSelect(attrs={'class':'rad'}))
    jenis_kendaraan = forms.ChoiceField(widget=forms.Select(), choices=JENIS_KENDARAAN)
    ###KENDARAAN

gadai/appgadai/biayamaterai/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms
from django.utils.safestring import mark_safe



class HorizRadioRenderer(forms.RadioSelect.renderer):
	def render(self):
		return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class Biaya_MateraiForm(ModelForm):
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    tanggal = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    nilai = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang','value':0,'size':10,}))
    #keterangan = forms.CharField( widget=forms.TextInput(attrs={'size':25,'placeholder':'Keterangan'}),required = False)
    antar_gerai = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=GERAI_PILIH,required = False)

    class Meta:
        model = Biaya_Materai
        widgets = {
            'saldo_awal' : forms.HiddenInput(),
            'saldo_akhir' : forms.HiddenInput(),
            'keterangan' : forms.HiddenInput(),
        }

gadai/appgadai/gudang/forms.py
from gadai.appkeuangan.models import DATACABANG
from django.forms import ModelForm,Select
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from django.core.exceptions import ValidationError
from chosen import forms as chosenforms
import datetime
from django.utils.safestring import mark_safe

JENIS_BARANG = (
	('500','GABUNGAN'),
	('1','HP'),('2','LAPTOP'),('3','KAMERA'),('4','PS'),
	('5','TV LCD'),('6','MOTOR'),('7','MOBIL'),
)

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self ]))

class SearchGudangForm(forms.Form):
    start_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    end_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    id_cabang = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=DATACABANG,initial='0',required=False)
    id_barang = forms.ChoiceField(widget=forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'id_pilih'}),choices = JENIS_BARANG)

gadai/appgadai/mankeu/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from gadai.appgadai.monthyearwidget import*

class Approve_MankeuForm(ModelForm):
    class Meta:
        model = ManopKeu

class LabaRugiMonthForm(forms.Form):    
    Bulan_Tahun = forms.DateField(required=False, widget=MonthYearWidget(years=xrange(2010,2050))
    )        

gadai/templates/barang/add.html
{% extends "base_aplikasi.html" %}
{% block content %}
<h2>Barang</h2>
<form method="post" action="." class="tabular">
{{ form.as_p }}
<p><label></label><input type="submit" value="Simpan" /></p>
</form>
{% endblock %}

gadai/templates/barang/edit2.html
{% extends "base_aplikasi.html" %}
{% block section %}customer{% endblock %}
{% block title %}Edit {{ object.nama }} - {{ block.super }}{% endblock %}
{% block content %}
<p class="breadcrumb"><a href="/">Dashboard</a> &gt; <a href="/customer/">Konsumen</a> &gt; Edit</p>
<h2>Edit Konsumen</h2>
<form method="POST" action="." class="tabular">
{{ form.as_p }}
<p><label></label><input type="submit" value="Simpan" /> <a href="/customer/" class="batal">batal</a></p>
</form>
{% endblock %}

gadai/templates/barang/lebih.html
{% extends "base_aplikasi.html" %}
{% block title %}Barang {{ block.super }}
{% endblock %}{% load useringroup %}
{% block section %}barang{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
{% load number_format useringroup %}

<h2 align="center">HISTORY TRANSAKSI DEBITUR  <small>Gerai {{gr.nama}}</small></h2>
<table class="tableizer-table"width="100%" border="1" align="center">
    <tr  class="tableizer-firstrow">
        <th>No</th>
        <th>Nama</th>
        <th>Jatuh tempo</th>
        <th>Nilai (Rp)</th>
        <th>History Transaksi</th>
        <th>History Barang Sama</th>
    </tr>

{% for a in ag%}
    <tr>
    <td align="center">{{ forloop.counter }}</td>
    <td> <a href="/nasabah/{{a.agnasabah.id}}/show/">{{ a.agnasabah.nama}}</a></td>
    <td>{{a.jatuhtempo|date:" d-M-Y"}}</td>
    <td align="right">{{ a.nilai|number_format:0}}</td>
    <td align="center">{{ a.agnasabah.lebih}}</td>    
    <td align="center">{{ a.barang.totallebih}}</td>
    {% endfor %}
</table>
{% endblock %}

gadai/templates/barang/popadd.html
<html>
    <head>
        <title>Add {{ field }}</title>
        <script type="text/javascript" src="/static/mediacss/js/admin/RelatedObjectLookups.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/mediacss/css/base.css" />
        <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
        <script type="text/javascript" src="/admin/jsi18n/"></script>
        <script type="text/javascript" src="/static/admin/js/core.js"></script>
        <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
        <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
        <script type="text/javascript" src="/static/admin/js/actions.js"></script>
        <script type="text/javascript" src="/static/admin/js/collapse.js"></script>
    </head>

  <body>
      <h1>Tambahkan {{ field }}</h1>
      <form method="POST" action="">
  <table>
    <tr><td><label for="id_jenis_barang">Jenis Barang:</label></td><td>{{form.jenis_barang}}</td></tr>
    <tr><td><label for="id_merk">Merk:</label></td><td>{{form.merk}}</td></tr>
    <tr><td><label for="id_type">Type:</label></td><td>{{form.type}}</td></tr>
    <tr><td><label for="id_sn">SN / IMEi:</label></td><td>{{form.sn}}</td></tr>
    <tr><td><label for="id_warna">Warna:</label></td><td>{{form.warna}}</td></tr>
    <tr><td><label for="id_tahun_pembuatan">Tahun Pembuatan:</label></td><td>{{form.tahun_pembuatan}}</td></tr>
    <tr><td><label for="id_bulan_produksi">Bulan Produksi:</label></td><td>{{form.bulan_produksi}}</td></tr>
    <tr><td><label for="id_accesoris_barang1">Accesoris Barang:</label></td><td>{{form.accesoris_barang1}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">Dokumen:</label></td><td>{{form.lampiran_dokumen}}</td></tr>
    <tr><td><label for="id_jenis_dokumen">Jenis Kendaraan:</label></td><td>{{form.jenis_kendaraan}}</td></tr>
    <tr><td><label for="id_merk_dokumen">Merk Kendaraan:</label></td><td>{{form.merk_kendaraan}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">Type Kendaraan:</label></td><td>{{form.type_kendaraan}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No Polisi:</label></td><td>{{form.no_polisi}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No Rangka:</label></td><td>{{form.no_rangka}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No Mesin:</label></td><td>{{form.no_mesin}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No Pembuatan:</label></td><td>{{form.tahun_pembuatan_kendaraan}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">Warna Kendaraan:</label></td><td>{{form.warna_kendaraan}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No BPKB:</label></td><td>{{form.no_bpkb}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">STNK Atas Nama:</label></td><td>{{form.stnk_atas_nama}}</td></tr>
    <tr><td><label for="id_lampiran_dokumen">No Faktur:</label></td><td>{{form.no_faktur}}</td></tr>

          
    <tr><td><label></td><td><input type="submit" value="simpan"/>| <a href="javascript:window.close()">Cancel </td></a></tr>
      </table>
      <!--<p><input type="submit"  /> | <a href="javascript:window.close()">Cancel</a></p>-->
    </form>
  </body>
</html>