gadai/accounts/urls.py
from django.conf.urls.defaults import patterns
from django.contrib.auth import views as authviews

urlpatterns = patterns('', 
    (r'^login/$',                authviews.login),
    (r'^logout/$',               authviews.logout_then_login),
    (r'^password/change/$',      authviews.password_change),
    (r'^password/change/done/$', authviews.password_change_done),
)

gadai/appgadai/kas/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail, create_update, date_based
from gadai.appgadai.models import MutasiKas, KasBank
from gadai.appgadai.kas.forms import MutasiKasForm
from gadai.appgadai.kas.views import rekening_show,mutasikas_add,mutasikas_bulan,rekening_pindahbuku
import datetime

MONTH_SHOW = 3 * 30
now = datetime.date.today()
since = now - datetime.timedelta(MONTH_SHOW)
date_list = MutasiKas.objects.filter(tanggal__gt=since).dates('tanggal', 'day')

cashflow_list = [{'tanggal': d,
        'penerimaan': sum([m.nilai for m in MutasiKas.objects.filter(tanggal=d) if m.is_debet]),
        'pengeluaran': sum([abs(m.nilai) for m in MutasiKas.objects.filter(tanggal=d) if not m.is_debet])} for d in date_list]


urlpatterns = patterns('',
    url(r'^$',  list_detail.object_list, {
        'queryset': MutasiKas.objects.all(),
        'template_name': 'kas/mutasikas_archive.html',
        'extra_context': {'cashflow_list': cashflow_list, 
            'date_list': MutasiKas.objects.dates('tanggal', 'month')}}),
    url(r'^add/$', mutasikas_add),
    url(r'^arsip/(?P<tahun>\d{4})/(?P<bulan>\d{2})/$', mutasikas_bulan),
    url(r'^rekening/(?P<object_id>\d+)/$', rekening_show),
    url(r'rekening/pindahbuku/', rekening_pindahbuku),
)

gadai/djangoChat/urls.py
from django.conf.urls import patterns, url

from djangoChat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^api/$',views.chat_api,name='chat_api'),
    url(r'^api/users/$',views.logged_chat_users,name='logged_chat_users'),
    url(r'^api/users/update/$',views.update_time,name='update_time')
)

gadai/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.static import serve
from django.views.generic import list_detail, create_update
admin.autodiscover()
from django.conf import settings
import os
from gadai.appgadai.views import homepage

urlpatterns = patterns('',
    url(r'^pencairan/',include('gadai.appgadai.pencairan.urls')),
    url(r'^gudang/',include('gadai.appgadai.gudang.urls')),
    url(r'^admgudang/',include('gadai.appgadai.admgudang.urls')),
    url(r'^parameter/',include('gadai.appkeuangan.parameter.urls')),
    url(r'^rreport/',include('gadai.appkeuangan.report.urls')),
    url(r'^rkeuangan/',include('gadai.appkeuangan.keuangan.urls')),
    url(r'^parameterjurnal/',include('gadai.appgadai.parameterjurnal.urls')),
    url(r'^materaicabang/',include('gadai.appgadai.materaicabang.urls')),
    url(r'^kplgerai/',include('gadai.appgadai.kplgerai.urls')),
    url(r'^mankeu/',include('gadai.appgadai.mankeu.urls')),
    url(r'^kasirgerai/', include('gadai.appgadai.kasirgerai.urls')),
    url(r'^manop/',include('gadai.appgadai.manop.urls')),
    url(r'^accounts/',include('gadai.accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',homepage),
    url(r'^setting/',    include('gadai.appgadai.setting.urls')),
    url(r'^akadgadai/', include('gadai.appgadai.akadgadai.urls')),
    url(r'^gerai/', include('gadai.appgadai.gerai.urls')),
    url(r'^nasabah/', include('gadai.appgadai.nasabah.urls')),
    url(r'^taksir/', include('gadai.appgadai.taksir.urls')),
    url(r'^jurnal/',include('gadai.appgadai.jurnal.urls')),
    url(r'^barang/',include('gadai.appgadai.barang.urls')),
    url(r'^pelunasan/',include('gadai.appgadai.pelunasan.urls')),
    url(r'^biaya/',include('gadai.appgadai.biaya.urls')),
    url(r'^lelang/',include('gadai.appgadai.lelang.urls')),##firman
    url(r'^piutang/',include('gadai.appgadai.piutang.urls')),
    url(r'^permintaan/',include('gadai.appgadai.permintaan.urls')),
    url(r'^report/',include('gadai.appgadai.report.urls')),
    url(r'^keuangan/',include('gadai.appgadai.keuangan.urls')),
    url(r'^biayamaterai/',include('gadai.appgadai.biayamaterai.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', serve, {'document_root' : os.path.join(os.path.dirname(__file__),("static"))})
    )

gadai/appgadai/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from datetime import datetime
import datetime
import calendar
import decimal
from dateutil.relativedelta import *
from gadai.appgadai.templatetags.number_format import number_format
from gadai.appkeuangan.models import *
from datetime import timedelta
from django.conf import settings
AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', User)

JENIS_AGUNAN = (
    ('1','HP'),('2','LAPTOP'),('3','KAMERA'),('4','PS'),('5','LCD'),('6','MOTOR'),('7','MOBIL'),
    )

CHOICES_PRODUK_PARAM =(
    ('1','1 Minggu'),('2','2 Minggu'),('3','3 Minggu'),('4','4 Minggu'),('5','1 Bulan'),('6','2 Bulan'),
    ('7','3 Bulan'),
)

GERAI_KEMBALI =(('','---------'),
    ('0','PUSAT'),('1','JAKARTA'),('2','SUCI'),('3','DIPATIUKUR'),('4','BALUBUR'),
    ('5','GERLONG HILIR'),('6','KOPO'),('7','CIBIRU'),('8','CIPACING'),('9','JATINANGOR'),
    ('10','CIMAHI'),('12','BUAHBATU'), ('15','MARANATA'),
    ('17','CIREBON PERJUANGAN'),('19','CIUMBULEUIT'),('20','UJUNGBERUNG'),('21','CIWASTRA'),('22','BOJONGSOANG')
)

GERAI_PILIH =(
    ('1','PUSAT'),('2','JAKARTA'),('3','SUCI'),('4','DIPATIUKUR'),('5','BALUBUR'),
    ('7','GERLONG HILIR'),('8','KOPO'),('9','CIBIRU'),('10','CIPACING'),('11','JATINANGOR'),
    ('12','CIMAHI'),('13','BUAHBATU'), ('16','MARANATA'),
    ('18','CIREBON PERJUANGAN'),('19','CIUMBULEUIT'),('20','UJUNGBERUNG'),('21','CIWASTRA'),('22','BOJONGSOANG')
)


STATUS = (
    ('1','CAIR'),
    ('2','NONE CAIR'),
)

JENIS_TRANSAKSI = (
    ('1','KAS'),
    ('2','BANK'),
)

STATUS_PENCAIRAN_NASABAH=(
    ('0','PENCAIRAN BARU'),
    ('1','PENCAIRAN GADAI ULANG'),
)

class KasirGeraiPelunasan(models.Model):
    kasir_lunas = models.OneToOneField('AkadGadai',null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS)
    tanggal = models.DateField()
    nilai_pembulatan_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    selisih_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    jenis_transaksi_lunas = models.CharField(max_length=1, choices=JENIS_TRANSAKSI)
    coa_sisa = models.CharField(max_length=30,null =True,blank=True)
    val_lunas = models.CharField(max_length = 3, null =True, blank=True)
    nilai_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    sisa_bayar_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    rek_tab = models.CharField(max_length=50,null =True,blank=True)
    nilai_titipan = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    cu = models.ForeignKey(User, related_name='+', editable=False, null=True, blank=True)
    mu = models.ForeignKey(User, related_name='+', editable=False, null=True, blank=True)

    class Meta:
        db_table = 'kasirgeraipelunasan'
        verbose_name = 'KasirGeraiPelunasan'
        verbose_name_plural = verbose_name
   
    def get_absolute_url(self):
        return "/kasirgeraipelunasan/" % self.id

    def kwlunas_validasi(self):
        return "KL %s 21.03.01 %s 11.01.04 %s WIB %s" % ((self.kasir_lunas.norek()),self.nilai_lunas,self.kasir_lunas.mdate,(str(self.kasir_lunas.gerai.init_cabang))) 

class KasirGerai(models.Model):
    kasir = models.OneToOneField('AkadGadai',null=True, blank=True)
    kasir_lunas = models.OneToOneField('Pelunasan',null=True,blank=True)
    status = models.CharField(max_length=1, choices=STATUS)
    tanggal = models.DateField()
    nilai_pembulatan = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    nilai_pembulatan_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    selisih = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    selisih_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    jenis_transaksi = models.CharField(max_length=1, choices=JENIS_TRANSAKSI)
    coa_sisa = models.CharField(max_length=30,null =True,blank=True)
    val = models.CharField(max_length = 3, null =True, blank=True)
    val_lunas = models.CharField(max_length=3,null=True,blank=True)
    cu = models.ForeignKey(User, related_name='c_kasirgerai', editable=False, null=True, blank=True)
    mu = models.ForeignKey(User, related_name='m_kasirgerai', editable=False, null=True, blank=True)
    nilai = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    sisa_bayar = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)

    nilai_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    sisa_bayar_lunas = models.DecimalField(max_digits=12,decimal_places=2,default=0,null=True,blank=True)
    tanggal_lunas = models.DateField(null=True, blank=True)
    jenis_transaksi_lunas = models.CharField(max_length=1, choices=JENIS_TRANSAKSI, null=True, blank=True)
    rek_tab = models.CharField(max_length=50,null =True,blank=True)

    class Meta:
        db_table = 'kasirgerai'
        verbose_name = 'KasirGerai'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return "/kasirgerai/" % self.id

    def __unicode__(self):
        return "%s-%s-%s" %(self.kasir.agnasabah.nama, self.kasir, self.id)


    def slip_validasi(self):
        sekarang=self.tanggal
        h=sekarang.day
        m=sekarang.month
        y=sekarang.year
        if self.selisih >= 0:
            return "|%s|%s|%s|%s|%s|%s" % ((self.kasir.mdate),(str(self.kasir.gerai.init_cabang)),self.nilai_pembulatan,self.kasir.nocoa_kas,self.selisih,self.coa_sisa)
        elif self.selisih < 0:
            return "|%s|%s|%s|%s|%s|%s" % ((self.kasir.mdate),(str(self.kasir.gerai.init_cabang)),self.nilai_pembulatan,self.kasir.nocoa_kas,(self.selisih * (-1)),self.coa_sisa)

def add_months(dt,months):
    month = dt.month - 1 + months
    year = dt.year + month / 12
    month = month % 12 + 1
    day = min(dt.day,calendar.monthrange(year,month)[1])
    return dt.replace(year=year, month=month, day=day)

JANGKA_WAKTU = (
    ('0','--- PILIH ---'),
    ('15','2 minggu'),
    ('31','31'),
)

JANGKA_WAKTU_KENDARAAN = (
    ('0','--- PILIH ---'),
    ('1','1'),
    #('2','2'),
    #('3','3'),
    #('4','4'),
)  

MERK_KENDARAAN_CHOICES = (
    ('0','--- PILIH ---'),
    ('1','HONDA'),
    ('2','SUZUKI'),
    ('3','TOYOTA'),
    ('4','NISAN'),
    ('5','MITSUBISHI'),
    ('6','DAIHATSHU'),
    ('7','YAMAHA'),
    ('8','CHEVROLET'),
    ('9','HYUNDAI'),
    ('10','KAWASAKI'),
    ('11','MAZDA'),
    ('12','PIAGGIO'),
    ('13','KIA'),
    ('14','FORD'),
    ('15','ISUZU'),
) 

GERAI = (
    ('1','1'),('2','2'),
    ('3','3'),('4','4'),
    ('5','5'),('6','6'),
    ('7','7'),('8','8'),
    ('9','9'),('10','10'),
    ('11','11'),('12','12'),    
    ('13','13'),('14','14'),
    ('15','15'),('16','16'),
    ('17','17'),('18','18'),
    ('19','19'),('20','20'),
    ('21','21'),('22','22'),
    ('23','23'),('24','24'),
)

AKUN = (
    ('3','3'),('4','4'),('5','5'),('6','6'),('7','7'),('8','8'),('131','131'),('132','132'),('133','133'),('134','134'),('135','135'),('136','137'),('138','138'),('139','139'),
    ('139','139'),('140','140'),('141','141'),('142','142'),('143','143'),('144','144'),('145','145'),('146','146'),('147','147'),('148','149'),('150','150'),('151','151'),
    ('152','152'),('153','153'),('154','154'),('155','155'),('156','156'),('157','157'),('158','158'),('159','159'),('160','160'),('161','161'),('162','162'),
    ('163','163'),('164','164'),('165','165'),('166','166'),('167','167'),('168','168'),('169','169'),('170','170'),('171','171'),('172','172'),('173','173'),
    ('174','174'),('175','175'),('176','176'),('177','177'),('178','178'),('178','178'),('179','179'),('180','180'),('181','181'),('182','182'),('183','183'),
    ('184','184'),('185','185'),('186','186'),('187','187'),('188','188'),('189','189'),('190','190'),('191','191'),('192','192'),('193','193'),('194','194'),
    ('195','195'),('196','196'),('197','197'),('198','198'),('199','199'),('200','200'),('201','201'),('202','202'),('203','203'),('204','204'),('205','205'),
    ('206','206'),('207','207'),('208','208'),('209','209'),('210','210'),('211','211'),('212','212'),('213','213'),('214','214'),('215','215'),('216','216'),
    ('217','217'),('218','218'),('219','219'),('220','220'),('221','221'),('222','222'),('223','223'),('224','224'),('225','225'),('226','226'),('227','227'),
    ('228','228'),('229','229'),('230','230'),('231','231'),('232','232'),('233','233'),('234','234'),('235','235'),('243','243'),('244','244'),('245','245'),
    ('246','246'),('247','247'),('248','248'),('249','249'),('250','250'),('251','251'),('252','252'),('253','253'),('254','254'),('255','255'),('256','256'),
    ('257','257'),('258','258'),('259','259'),('260','260'),('265','265'),('266','266'),('267','267'),('268','268'),('269','269'),('270','270'),('271','271'),
    ('272','272'),('273','273'),('274','274'),('286','286'),('287','287'),('288','288'),('293','293'),('294','294'),('295','295'),('297','297'),('298','298'),
    ('307','307'),('308','308'),('311','311'),('312','312'),('313','313'),('314','314'),('315','315'),('316','316'),('317','317'),('318','318'),('319','319'),
    ('320','320'),('321','321'),('322','322'),('323','323'),('324','324'),('325','325'),('326','326'),('327','327'),('328','328'),('329','329'),('330','330'),
    ('331','331'),('332','332'),('333','333'),('334','334'),('335','335'),('336','336'),('337','337'),('359','359'),('360','360'),('361','361'),('362','362'),
    ('363','363'),('364','364'),('365','365'),('366','366'),('367','367'),('368','368'),('369','369'),('370','370'),('371','371'),('372','372'),('373','373'),

gadai/appgadai/admgudang/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms

class AdmGudangForm(forms.ModelForm):
    tanggal = forms.DateField(widget=forms.widgets.DateInput(attrs={'readonly':'False'}, format="%d-%m-%Y"))
    class Meta:
        model = AdmGudang
        widgets = {
            'adm' : forms.HiddenInput(),
        }

gadai/appgadai/biayamaterai/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms
from django.utils.safestring import mark_safe



class HorizRadioRenderer(forms.RadioSelect.renderer):
	def render(self):
		return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class Biaya_MateraiForm(ModelForm):
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    tanggal = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    nilai = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang','value':0,'size':10,}))
    #keterangan = forms.CharField( widget=forms.TextInput(attrs={'size':25,'placeholder':'Keterangan'}),required = False)
    antar_gerai = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=GERAI_PILIH,required = False)

    class Meta:
        model = Biaya_Materai
        widgets = {
            'saldo_awal' : forms.HiddenInput(),
            'saldo_akhir' : forms.HiddenInput(),
            'keterangan' : forms.HiddenInput(),
        }

gadai/appgadai/gudang/forms.py
from gadai.appkeuangan.models import DATACABANG
from django.forms import ModelForm,Select
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from django.core.exceptions import ValidationError
from chosen import forms as chosenforms
import datetime
from django.utils.safestring import mark_safe

JENIS_BARANG = (
	('500','GABUNGAN'),
	('1','HP'),('2','LAPTOP'),('3','KAMERA'),('4','PS'),
	('5','TV LCD'),('6','MOTOR'),('7','MOBIL'),
)

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self ]))

class SearchGudangForm(forms.Form):
    start_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    end_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    id_cabang = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=DATACABANG,initial='0',required=False)
    id_barang = forms.ChoiceField(widget=forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'id_pilih'}),choices = JENIS_BARANG)

gadai/appgadai/mankeu/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from gadai.appgadai.monthyearwidget import*

class Approve_MankeuForm(ModelForm):
    class Meta:
        model = ManopKeu

class LabaRugiMonthForm(forms.Form):    
    Bulan_Tahun = forms.DateField(required=False, widget=MonthYearWidget(years=xrange(2010,2050))
    )        

gadai/templates/taksir/add.html
{% extends "base_aplikasi.html" %}
{% block extrahead %}
<link type="text/css" href="/static/css/smoothness/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />
<script src="/static/js/jquery-ui-1.7.1.custom.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.meio.mask.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#id_tanggal").datepicker({dateFormat: 'dd-mm-yy'});
    $("#id_tglupdate").datepicker({dateFormat: 'dd-mm-yy'});
    $('input:text').setMask();
       $('.tabular').submit(function(){
        $('input.uang').each(function () { $(this).val(to_number($(this).val())); });
        return true;
    });
});
</script>
{% endblock %}
{% block section %}gadai{% endblock %}
{% block content %}
<h2 align="right">:: INPUT DATA TAKSIR BARANG ::</h2>
<form class="tabular" method="POST" action=".">{% csrf_token %}
<table align="center">
{{ form }}
</table>
<p align="center"><label>&nbsp;</label><input type="submit" value="Simpan" /></p>
</form>
{% endblock %}

gadai/templates/taksir/confirm_delete.html
{% extends "base_aplikasi.html" %}
{% block section %}Taksir{% endblock %}{% load number_format %}
{% block content %}
<h2>Dana</h2>
<h3>Menghapus data Taksir</h3>
<p>Yakin akan menghapus data Taksir <strong>{{ object.type }}</strong> tanggal {{ object.tanggal|date:"d F Y" }} Kode Barang<strong> {{ object.kobar}}</strong>?</p>
<form action="." method="POST">
{% include "elements/submit_batal.html" %}
</form>
{% endblock %}

gadai/templates/taksir/edit.html
{% extends "base_aplikasi.html" %}
{% block extrahead %}
<link type="text/css" href="/static/css/smoothness/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />
<script src="/static/js/jquery-ui-1.7.1.custom.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.meio.mask.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#id_tanggal").datepicker({dateFormat: 'yy-mm-dd'});
    $("#id_tglupdate").datepicker({dateFormat: 'yy-mm-dd'});
    $('input:text').setMask();
       $('.tabular').submit(function(){
        $('input.uang').each(function () { $(this).val(to_number($(this).val())); });
        return true;
    });
});
</script>
{% endblock %}
{% block section %}gadai{% endblock %}
{% block content %}
<p class="breadcrumb"></p>
<h2 align="right">EDIT NILAI TAKSIR KSU RIZKY ABADI</h2>
<form class ="tabular" method='POST' action="." >{% csrf_token %} 
<table align="center">
{{ form }}
</table>
<p align="center"><label>&nbsp;</label><input type="submit" value="Simpan" /></p>
</form>
{% endblock %}

gadai/templates/taksir/index.html
{% extends "base_aplikasi.html" %}
{% block title %}{{ block.super }}
{% endblock %}
{% block section %}{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
{% load number_format useringroup %}

<h2 align="right">:: Daftar Taksiran Barang Gadai ::</h2><body>
    {% if error %}
        <p style="color: red;">Please submit a search term.</p>
    {% endif %}
    <form action="/taksir/cari/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
    <br/>
</body>
<table align = "center">
<div class="pagination" align="center">
    <span class="step-links">
        {% if taksir.has_previous %}
            <a href="?page={{ taksir.previous_page_number }}" class="next">Back</a>
        {% endif %}

        <span class="current">
            Halaman {{ taksir.number }} Dari {{ taksir.paginator.num_pages }}.
        </span>

        {% if taksir.has_next %}
            <a href="?page={{ taksir.next_page_number }}" class="next">Next</a>
        {% endif %}
    </span>
</div>
</table>

<table class="tableizer-table"width="100%" border="1" align="center">
    <tr  class="tableizer-firstrow"><th>No</th><th>Kode Barang</th><th>Type</th><th>Nama barang</th><th>Harga Baru</th><th>Harga Pasar</th><th>Max Pinjaman</th><th>Tanggal</th><th>Status</th><th>Menu</th></tr>
{% for taksir in taksir.object_list%}
    <tr>
    <td>{{ forloop.counter }}</td>
    <th><a href="/taksir/{{taksir.id}}/show/">{{ taksir.kobar}}</a></th>
    <td>{{ taksir.type }}</td>
    <td>{{ taksir.spesifikasi }}</td>
    <td>{{ taksir.harga_baru|number_format:0}}</td>
    <td>{{ taksir.harga_pasar|number_format:0}}</td>
    <td>{{ taksir.maxpinjaman|number_format:0}}</td>
    <td>{{ taksir.tglupdate|date:" d-M-Y"}}</td>
    <td>{{taksir.get_status_display}}</td>
    <td>{% ifusergroup pusat|staffops%} <a href="/taksir/{{taksir.id }}/edit/"><img src="/static/images/edit.png" height="27px"/>{% endifusergroup %}
{% endfor %}</td>
</table>
 <table align = "center">
<div class="pagination" align="center">
    <span class="step-links">
        {% if taksir.has_previous %}
            <a href="?page={{ taksir.previous_page_number }}" class="next">Back</a>
        {% endif %}

        <span class="current" class="next">
            Halaman {{ taksir.number }} Dari {{ taksir.paginator.num_pages }}.
        </span>

        {% if taksir.has_next %}
            <a href="?page={{ taksir.next_page_number }}" class="next">Next</a>
        {% endif %}
    </span>
</div>
</table>
 

{% endblock %}

gadai/templates/taksir/show.html
{% extends "base_aplikasi.html" %}
{% block title %}{{ block.super }}
{% endblock %}
{% block section %}{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
{% load number_format useringroup %}

<h2 align="right">:: Daftar Taksiran Barang Gadai ::</h2>
<table table width="100%" border="1" align="center">
<tr class="{% cycle 'odd' 'even' %}">
    <th>Kode Barang</th>
    <th>Type</th>
    <th>Nama barang</th>
    <th>Harga Baru</th>
    <th>Harga Pasar</th>
    <th>Max Pinjaman</th>
    <th>Tanggal Update</th>
    <th colspan= "2">MENU</th>
</tr>

<tr>
    <th>{{ tkr.kobar}}</th>
    <td>{{ tkr.type }}</td>
    <td>{{ tkr.spesifikasi }}</td>
    <td>{{ tkr.harga_baru}}</td>
    <td>{{ tkr.harga_pasar}}</td>
    <td>{{ tkr.maxpinjaman}}</td>
    <td>{{ tkr.tglupdate|date:" d-M-Y"}}</td>
    <td><a href="/taksir/{{tkr.id }}/edit/"><img src="/static/images/edit.png" height="27px"/></td></tr>

</table>
{% endblock %}