gadai/accounts/urls.py
from django.conf.urls.defaults import patterns
from django.contrib.auth import views as authviews

urlpatterns = patterns('', 
    (r'^login/$',                authviews.login),
    (r'^logout/$',               authviews.logout_then_login),
    (r'^password/change/$',      authviews.password_change),
    (r'^password/change/done/$', authviews.password_change_done),
)

gadai/appgadai/kas/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail, create_update, date_based
from gadai.appgadai.models import MutasiKas, KasBank
from gadai.appgadai.kas.forms import MutasiKasForm
from gadai.appgadai.kas.views import rekening_show,mutasikas_add,mutasikas_bulan,rekening_pindahbuku
import datetime

MONTH_SHOW = 3 * 30
now = datetime.date.today()
since = now - datetime.timedelta(MONTH_SHOW)
date_list = MutasiKas.objects.filter(tanggal__gt=since).dates('tanggal', 'day')

cashflow_list = [{'tanggal': d,
        'penerimaan': sum([m.nilai for m in MutasiKas.objects.filter(tanggal=d) if m.is_debet]),
        'pengeluaran': sum([abs(m.nilai) for m in MutasiKas.objects.filter(tanggal=d) if not m.is_debet])} for d in date_list]


urlpatterns = patterns('',
    url(r'^$',  list_detail.object_list, {
        'queryset': MutasiKas.objects.all(),
        'template_name': 'kas/mutasikas_archive.html',
        'extra_context': {'cashflow_list': cashflow_list, 
            'date_list': MutasiKas.objects.dates('tanggal', 'month')}}),
    url(r'^add/$', mutasikas_add),
    url(r'^arsip/(?P<tahun>\d{4})/(?P<bulan>\d{2})/$', mutasikas_bulan),
    url(r'^rekening/(?P<object_id>\d+)/$', rekening_show),
    url(r'rekening/pindahbuku/', rekening_pindahbuku),
)

gadai/djangoChat/urls.py
from django.conf.urls import patterns, url

from djangoChat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^api/$',views.chat_api,name='chat_api'),
    url(r'^api/users/$',views.logged_chat_users,name='logged_chat_users'),
    url(r'^api/users/update/$',views.update_time,name='update_time')
)

gadai/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.static import serve
from django.views.generic import list_detail, create_update
admin.autodiscover()
from django.conf import settings
import os
from gadai.appgadai.views import homepage

urlpatterns = patterns('',
    url(r'^pencairan/',include('gadai.appgadai.pencairan.urls')),
    url(r'^gudang/',include('gadai.appgadai.gudang.urls')),
    url(r'^admgudang/',include('gadai.appgadai.admgudang.urls')),
    url(r'^parameter/',include('gadai.appkeuangan.parameter.urls')),
    url(r'^rreport/',include('gadai.appkeuangan.report.urls')),
    url(r'^rkeuangan/',include('gadai.appkeuangan.keuangan.urls')),
    url(r'^parameterjurnal/',include('gadai.appgadai.parameterjurnal.urls')),
    url(r'^materaicabang/',include('gadai.appgadai.materaicabang.urls')),
    url(r'^kplgerai/',include('gadai.appgadai.kplgerai.urls')),
    url(r'^mankeu/',include('gadai.appgadai.mankeu.urls')),
    url(r'^kasirgerai/', include('gadai.appgadai.kasirgerai.urls')),
    url(r'^manop/',include('gadai.appgadai.manop.urls')),
    url(r'^accounts/',include('gadai.accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',homepage),
    url(r'^setting/',    include('gadai.appgadai.setting.urls')),
    url(r'^akadgadai/', include('gadai.appgadai.akadgadai.urls')),
    url(r'^gerai/', include('gadai.appgadai.gerai.urls')),
    url(r'^nasabah/', include('gadai.appgadai.nasabah.urls')),
    url(r'^taksir/', include('gadai.appgadai.taksir.urls')),
    url(r'^jurnal/',include('gadai.appgadai.jurnal.urls')),
    url(r'^barang/',include('gadai.appgadai.barang.urls')),
    url(r'^pelunasan/',include('gadai.appgadai.pelunasan.urls')),
    url(r'^biaya/',include('gadai.appgadai.biaya.urls')),
    url(r'^lelang/',include('gadai.appgadai.lelang.urls')),##firman
    url(r'^piutang/',include('gadai.appgadai.piutang.urls')),
    url(r'^permintaan/',include('gadai.appgadai.permintaan.urls')),
    url(r'^report/',include('gadai.appgadai.report.urls')),
    url(r'^keuangan/',include('gadai.appgadai.keuangan.urls')),
    url(r'^biayamaterai/',include('gadai.appgadai.biayamaterai.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', serve, {'document_root' : os.path.join(os.path.dirname(__file__),("static"))})
    )

gadai/appgadai/admgudang/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms

class AdmGudangForm(forms.ModelForm):
    tanggal = forms.DateField(widget=forms.widgets.DateInput(attrs={'readonly':'False'}, format="%d-%m-%Y"))
    class Meta:
        model = AdmGudang
        widgets = {
            'adm' : forms.HiddenInput(),
        }

gadai/appgadai/biayamaterai/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from chosen import forms as chosenforms
from django.utils.safestring import mark_safe



class HorizRadioRenderer(forms.RadioSelect.renderer):
	def render(self):
		return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class Biaya_MateraiForm(ModelForm):
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    tanggal = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    nilai = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang','value':0,'size':10,}))
    #keterangan = forms.CharField( widget=forms.TextInput(attrs={'size':25,'placeholder':'Keterangan'}),required = False)
    antar_gerai = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=GERAI_PILIH,required = False)

    class Meta:
        model = Biaya_Materai
        widgets = {
            'saldo_awal' : forms.HiddenInput(),
            'saldo_akhir' : forms.HiddenInput(),
            'keterangan' : forms.HiddenInput(),
        }

gadai/appgadai/gerai/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from django.core.exceptions import ValidationError
from chosen import forms as chosenforms
from django.utils.safestring import mark_safe
from django.forms import ModelForm,Select

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

JENIS_REPORT =(
    ('1','PDF'),
)

class aktifasi_userForm(forms.Form):
    id_cabang = chosenforms.ChosenModelChoiceField(label = "Gerai",queryset=Tbl_Cabang.objects.all(),widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_account'}))


class Filter_NeracaForm(forms.Form):
    report = forms.ChoiceField(widget = forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'id_report'}), choices = JENIS_REPORT)
    id_cabang = chosenforms.ChosenModelChoiceField(label = "Gerai",queryset=Tbl_Cabang.objects.all(),widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_account'}))
    start_date = forms.DateField(initial= datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,'readonly':'false'}, format="%Y-%m-01"))


class ManopForm(forms.Form):
    tanggal_manop = forms.DateField(initial=datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'true'}, format="%d-%m-%Y"))
    comment = forms.CharField(widget=forms.TextInput( attrs={'size': 15,'placeholder':'Isi Data Diskon'}))

class PelunasanForm(ModelForm):
    pelunasan = forms.ModelChoiceField(queryset=AkadGadai.objects.filter(lunas__isnull=True),widget=forms.HiddenInput())
    status_pelunasan = forms.ChoiceField(choices=STATUS_LUNAS,widget=forms.RadioSelect(attrs={'class':'rad'}),initial=1,)
    tanggal = forms.DateField(widget=forms.TextInput(attrs={'size': 8}))
    nilai = forms.DecimalField(widget=forms.TextInput(attrs={'readonly':'True','size': 8}))
    denda = forms.DecimalField(widget=forms.TextInput(attrs={'size': 8,'value':0}))
    terlambat = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2,'value': '0'}))
    bea_jasa = forms.DecimalField(widget=forms.TextInput(attrs={'size': 8,'value':0}))
    jenis_barang = forms.ChoiceField(choices=CHOICES_JENIS_TRANSAKSI,widget=forms.RadioSelect(attrs={'class':'rad'}))
    denda_kendaraan = forms.DecimalField(widget=forms.TextInput(attrs={'size': 8,'value': '0'}))
    terlambat_kendaraan = forms.IntegerField(widget=forms.TextInput(attrs={'size': 2}))
    bea_jasa_kendaraan = forms.DecimalField(widget=forms.TextInput(attrs={'size': 8,'value':0}))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all(),widget=forms.HiddenInput())

    
    class Meta:
        model = Pelunasan 

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class BarangBedaOtoForm(forms.Form):
    #pilih_jasa = forms.ChoiceField(widget=forms.Select(attrs={'readonly':'True'}),choices=JASABARU)
    pilih_jasa = forms.ChoiceField(widget = forms.HiddenInput(),choices=JASABARU,initial='1')
    agnasabah = forms.ModelChoiceField(label = "NAMA NASABAH",queryset=Nasabah.objects.filter(id__isnull=False))
    tanggal = forms.DateField(initial=datetime.date.today,widget=forms.widgets.DateInput(attrs={'readonly':'false'}, format="%d-%m-%Y"))
    gerai = forms.ModelChoiceField(queryset=Tbl_Cabang.objects.all())
    
    nilai = forms.IntegerField(label="Nilai",widget=forms.TextInput(attrs={'id':'nilai','alt': 'integer', 'class': 'rp_plafon uang','onkeyup':'hitungJasa(),akumulasi()'}))
    kewajiban_pelunasan = forms.IntegerField(label="Nilai",widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    taksir = chosenforms.ChosenModelChoiceField(label = "Data Taksir",queryset=Taksir.objects.filter(status =2),\
        widget=chosenforms.ChosenMultipleChoiceField({'class': 'kode_account'}))
    barang = forms.ModelChoiceField(label="Nama Barang",queryset=Barang.objects.all(),widget=forms.Select(attrs={'readonly':'readonly'}))
    bea_materai = forms.IntegerField(widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang','value':'0',\
        'id':'materai','onkeyup':'akumulasi()'}))
    jenis_transaksi=forms.ChoiceField(choices=CHOICES_JENIS_TRANSAKSI,widget=forms.RadioSelect(attrs={'class':'rad','id':'jenis_transaksi'}))    
    jangka_waktu = forms.ChoiceField( widget = forms.Select(attrs={'id':'jangka_waktu','onchange':'hitungJasa(),akumulasi()'}),\
        choices = JANGKA_WAKTU)
    ###KENDARAAN
    jangka_waktu_kendaraan = forms.ChoiceField( widget = forms.Select(attrs={'id':'jangka_waktu_kendaraan','onchange':'hitungJasa(),akumulasi()'}),\
        choices = JANGKA_WAKTU_KENDARAAN)
    jenis_kendaraan = forms.ChoiceField(widget=forms.Select(attrs={'id':'id_jenis_kendaraan','onchange':'hitungJasa(),akumulasi()'}), choices=JENIS_KENDARAAN)

    ### Barang ELEKTRONIK###
    jenis_barang = forms.ChoiceField(widget = forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'barang',}), choices = JENIS_BARANG,required=False)
    
    ###new input 1 april
    charger = forms.ChoiceField(widget =forms.Select(attrs={'class':'formhp formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_charger = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formhp formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')    
    batre = forms.ChoiceField(widget =forms.Select(attrs={'class':'formhp formbarang formkamera'}), choices=CHOICES_BARANG, initial='2')
    kondisi_batre = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formhp formbarang formkamera'}), choices=CHOICES_KONDISI_BARANG,initial='5')        
    keybord = forms.ChoiceField(widget =forms.Select(attrs={'class':'formhp formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_keybord = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formhp formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')        
    cassing = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_cassing = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')        
    layar = forms.ChoiceField(widget =forms.Select(attrs={'class':'formhp formbarang '}), choices=CHOICES_BARANG, initial='2')
    kondisi_layar = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formhp formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    password = forms.ChoiceField(widget =forms.Select(attrs={'class':'formhp formbarang '}), choices=CHOICES_BARANG, initial='2')
    password_barang = forms.CharField(label="PASSWORD ", widget=forms.TextInput( attrs={'size': 15,'class':'formhp formbarang ','placeholder':'Isi Sesuai Password','value': '0'}))
    
    lensa = forms.ChoiceField(widget =forms.Select(attrs={'class':'formkamera formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_lensa = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formkamera formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    batre_kamera = forms.ChoiceField(widget =forms.Select(attrs={'class':'formkamera formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_batre_kamera = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formkamera formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    cassing_kamera = forms.ChoiceField(widget =forms.Select(attrs={'class':'formkamera formbarang'}), choices=CHOICES_BARANG, initial='2')
    kondisi_cassing_kamera = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formkamera formbarang'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    
    optik_ps = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formps'}), choices=CHOICES_BARANG, initial='2')
    kondisi_optik_ps = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formps'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    harddisk  = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formps'}), choices=CHOICES_BARANG, initial='2')
    kondisi_harddisk = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formps'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    stick  = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formps'}), choices=CHOICES_BARANG, initial='2')
    kondisi_stick = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formps'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    hdmi  = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formps'}), choices=CHOICES_BARANG, initial='2')
    kondisi_hdmi = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formps'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    remote = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formtv'}), choices=CHOICES_BARANG, initial='2')
    kondisi_remote = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formbarang formtv'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    dus = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang'}), choices=CHOICES_BARANG, initial='2')
    tas = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang'}), choices=CHOICES_BARANG, initial='2')
    layar_tv = forms.ChoiceField(widget =forms.Select(attrs={'class':'formbarang formtv'}), choices=CHOICES_BARANG, initial='2')
    kondisi_layar_tv = forms.ChoiceField(widget =forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'formbarang formtv'}), choices=CHOICES_KONDISI_BARANG,initial='5')
    

gadai/appgadai/gudang/forms.py
from gadai.appkeuangan.models import DATACABANG
from django.forms import ModelForm,Select
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import *
from django.core.exceptions import ValidationError
from chosen import forms as chosenforms
import datetime
from django.utils.safestring import mark_safe

JENIS_BARANG = (
	('500','GABUNGAN'),
	('1','HP'),('2','LAPTOP'),('3','KAMERA'),('4','PS'),
	('5','TV LCD'),('6','MOTOR'),('7','MOBIL'),
)

class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self ]))

class SearchGudangForm(forms.Form):
    start_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    end_date = forms.DateField(initial = datetime.date.today,widget=forms.widgets.DateInput(attrs={'size': 12,}, format="%Y-%m-%d"))
    id_cabang = chosenforms.ChosenChoiceField(widget=forms.Select(), choices=DATACABANG,initial='0',required=False)
    id_barang = forms.ChoiceField(widget=forms.RadioSelect(renderer=HorizRadioRenderer,attrs={'class':'id_pilih'}),choices = JENIS_BARANG)

gadai/appgadai/lelang/forms.py
from django import forms
from django.forms import ModelForm
from gadai.appgadai.models import BarangLelang,AkadGadai

class BarangLelangForm(forms.ModelForm):
    aglelang =forms.ModelChoiceField(queryset=AkadGadai.objects.all())
    tgl_lelang = forms.DateTimeField(label = "Tanggal Pelelangan",widget=forms.TextInput(attrs={'size': 10}))
    harga_jual = forms.IntegerField(label="Nilai Taksir",widget=forms.TextInput(attrs={'alt': 'integer', 'class': 'uang'}))
    nama_pembeli =forms.CharField(widget=forms.TextInput(attrs={'size': 70}))

    class Meta:
        model = BarangLelang

gadai/templates/manop/lainlain/rincian_lainlain.html
{% extends "base_aplikasi.html" %}
{% block extrahead %}
{% include "alat/ledger.html" %}
{% endblock %}
{% block section %}hilang{% endblock %}
{% block content %}
{% load number_format useringroup %}

<h2>DATA BARANG LAINNYA UNIT PJB </h2>  
<form method="GET" action="/manop/rincian_lainlain/">{% csrf_token %}
   <table id="tabel" align="center">
    <li><label for="id_cabang">Kode Cabang</label> :
      <select id="id_id_cabang" data-placeholder="None" class="chosen-select" name="id_cabang">
            <option value="" selected="selected">---------</option><option value="500">(Gabungan)</option>
            <option value="300">PUSAT-pjb</option><option value="301">JAKARTA</option><option value="302">SUCI</option><option value="303">DIPATIUKUR</option>
            <option value="304">BALUBUR</option><option value="306">GERLONG HILIR</option><option value="307">KOPO</option><option value="308">CIBIRU</option>
            <option value="309">CIPACING</option><option value="310">JATINANGOR</option><option value="311">CIMAHI</option><option value="312">BUAH BATU</option>
            <option value="313">KORDON</option><option value="314">CIHANJUANG</option><option value="315">MARANATHA</option><option value="316">KIARACONDONG</option>
            <option value="317">CIREBON PERJUANGAN</option><option value="319">CIUMBELEUIT</option><option value="320">UJUNGBERUNG</option><option value="321">CIWASTRA</option>
            <option value="322">BOJONGSOANG</option><option value="323">CIJERAH</option><option value="324">KATAPANG</option><option value="325">CIMINDI</option>
            <option value="326">CEMARA</option><option value="327">LEUWI GAJAH</option>
     </select>      
   </li>
   <br>
   <li><label for="id_tgl_trans">Tanggal </label> :<input type="text" name="start_date" id="id_start_date" size="15" value="{% now "Y-m" %}-01" /> 
   <label for="id_tgl_trans">Tanggal </label> :<input type="text" name="end_date" id="id_end_date" size="15" value="{% now "Y-m-d" %}"/></li>
   <br>
   <li><input type="submit" value="CETAK XLS" class="cari" name="submit_tiga"/>&nbsp; 
	  <input type="submit" value="CETAK PDF" class="cari" name="submit_dua"/> &nbsp;
	  <input type="submit" value="VIEW" class="cari" name="submit_satu" value="Add"/>
   </li>
   </table>
</form>
<br>
<hr>
   {%if kp%}
<h3 style='text-align: center'><b><small>DATA BARANG LAINNYA</small></b><b><small> UNIT PJB <small><small>
</small>
{% if id_cabang = '500' %}(GABUNGAN){%endif%}
   {% if id_cabang = '1' %}BANDUNG{%endif%}{% if id_cabang = '2' %}Gerai: JAKARTA{%endif%}
   {% if id_cabang = '3' %}Gerai: SUCI{%endif%}{% if id_cabang = '4' %}Gerai: DIPATIUKUR{%endif%}
   {% if id_cabang = '5' %}Gerai: BALUBUR{%endif%}{% if id_cabang = '6' %}Gerai: GERLONG GIRANG{%endif%}
   {% if id_cabang = '7' %}Gerai: GEGER KALONG HILIR{%endif%}{% if id_cabang = '8' %}Gerai: KOPO{%endif%}
   {% if id_cabang = '9' %}Gerai: CIBIRU{%endif%}{% if id_cabang = '10' %}Gerai: CIPACING{%endif%}
   {% if id_cabang = '11' %}Gerai: JATINANGOR{%endif%}{% if id_cabang = '12' %}Gerai: CIMAHI{%endif%}
   {% if id_cabang = '13' %}Gerai: BUAH BATU{%endif%}{% if id_cabang = '14' %}Gerai: KORDON{%endif%}
   {% if id_cabang = '15' %}Gerai: CIHANJUANG{%endif%}{% if id_cabang = '16' %}Gerai: MARANATHA{%endif%}
   {% if id_cabang = '17' %}Gerai: KIARA CONDONG{%endif%}{% if id_cabang = '18' %}Gerai: CIREBON PERJUANGAN{%endif%}
   {% if id_cabang = '19' %}Gerai: CIREBON RAYAT{%endif%}{% if id_cabang = '20' %}Gerai: CIUMBULEUIT{%endif%}
   {% if id_cabang = '21' %}Gerai: UJUNG BERUNG{%endif%}

</small> </b>
</h3>
<h4 style='text-align: center'><small>Periode : {{start_date}} - {{end_date}}</small></h4>
<form method="POST" action="/manop/reset_status_lainlain/">{% csrf_token %}
<table class="tableizer-table"width="100%" border="1">
<tr class="tableizer-firstrow">
    <th>No</th>
    <th>No Rekening</th>
    <th>Gerai</th>
    <th>Nama</th>
    <th>Barang</th>
    <th>Status</th>
    <th>Tgl Status </th>
    <th>Tanggal</th>
    <th>JW (hari)</th>
    <th>Jatuh Tempo</th>
    <th>Nilai</th>
</tr>

{% for p in kp %}
<tr>
    <td align="center"><input type="checkbox"  value="{{ p.id }}" class="checkbox_delete" name='id_pilih' />{{ forloop.counter }}</td>
    <td align="center">{{ p.norek }}</td>
    <td>{{ p.gerai }}</td>
    <td>{{ p.agnasabah.nama|truncatewords:2 }}</td>
    <td>{{p.barang.merk}}.{{p.barang.type}}</td>
    <td>{{ p.status_transaksi}}</td>
    <td>{{p.tanggal_lelang|date:"d-M-Y"}}
    <td>{{ p.tanggal|date:"d-M-Y"}}</td>
    <td align="center">{% if p.jangka_waktu_kendaraan  %}{{ p.jangka_waktu_kendaraan|default_if_none:"" }} Bulan{%else%}
                       {{ p.jangka_waktu|default_if_none:"" }} Hari</td>{% endif %}
    <td align="center">{{ p.jatuhtempo|date:" d-M-Y"}}</abbr></td>
    <td align="right">{{ p.nilai|number_format:0|default_if_none:"0" }}</td>
</tr>
{% endfor %}
<tr>
    <th colspan="10"><strong>Jumlah</strong></th>
    <th align="right" >{{nilai|number_format:0}}</th>
</tr>
</table>
<p align="right"><input type="submit" value="RESET STATUS" class="cari" /></p>
</form>
{% else %}
<p>Tidak ada data </p>
{% endif %}
<link rel="stylesheet" href="/static/chosen/static/css/chosen.css">
<script src="/static/chosen/static/js/chosen.jquery.js" type="text/javascript"></script>
<script type="text/javascript">
    $(".chosen-select").chosen()
</script>
{% endblock %}